# define task execution and order
# 0 means the task won't run, and then tasks are ordered starting with 1
# Ensure that no tasks are set to the same number (except 0)
task_execution_order:
  navigation_channel:     1
  speed_run:              0
  docking:                0
  mag_route:              0

navigation_channel_1_lat: 1.0
navigation_channel_1_lon: 1.0
navigation_channel_2_lat: 1.0
navigation_channel_2_lon: 1.0

speed_run_1_lat: 1.0
speed_run_1_lon: 1.0
speed_run_2_lat: 1.0
speed_run_2_lon: 1.0

docking_1_lat: 1.0
docking_1_lon: 1.0
docking_2_lat: 1.0
docking_2_lon: 1.0

mag_route_1_lat: 1.0
mag_route_1_lon: 1.0
mag_route_2_lat: 1.0
mag_route_1_lon: 1.0