# define task execution and order
# 0 means the task won't run, and then tasks are ordered starting with 1
# Ensure that no tasks are set to the same number (except 0)
navigation_channel_order:         1
speed_run_order:                  2
docking_order:                    0
mag_route_order:                  0
