# define task execution and order
# 0 means the task won't run, and then tasks are ordered starting with 1
# Ensure that no tasks are set to the same number (except 0)
task_execution_order:
  navigation_channel:     1
  speed_run:              2
  docking:                0
  mag_route:              0


task_start_points:
  navigation_channel_lat:     1
  navigation_channel_lon:
  speed_run_lat:              2
  speed_run_lon:
  docking_run_lat:            0
  docking_run_lon:
  mag_route_lat:              0
  mag_route_lon:             0 